---
- name: "create dirs"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ imagemagick_install_path }}"
  tags: imagemagick

- name: "get source"
  get_url:
    url: "{{ imagemagick_source_url }}"
    dest: "/usr/local/src/ImageMagick-{{ imagemagick_version }}.tar.xz"
  tags: imagemagick

- name: "install dependencies"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - "{{ imagemagick_dependencies }}"
    - "{{ imagemagick_optional_dependencies }}"
  tags: imagemagick

- name: "extract archive"
  unarchive:
    src: "/usr/local/src/ImageMagick-{{ imagemagick_version }}.tar.xz"
    dest: "/usr/local/src/"
    copy: no
    creates: "{{ imagemagick_source_path }}"
  tags: imagemagick

- name: "configure"
  command: "./configure --prefix={{ imagemagick_install_path }} {{ imagemagick_configure_options }}"
  args:
    chdir: "{{ imagemagick_source_path }}"
    creates: "{{ imagemagick_source_path }}/config.status"
  tags: imagemagick

- name: "build"
  command: "make -j{{ ansible_processor_cores|default(1) }}"
  args:
    chdir: "{{ imagemagick_source_path }}"
    creates: "{{ imagemagick_source_path }}/utilites/.libs"
  tags: imagemagick

- name: "install"
  command: "make install"
  args:
    chdir: "{{ imagemagick_source_path }}"
  tags: imagemagick

- name: "get binaries"
  find:
    file_type: link
    paths: "{{ imagemagick_install_path }}/bin/"
  register: imagemagick_binaries
  tags: imagemagick

- name: "add binaries to /usr/bin"
  alternatives:
    name: "{{ item.path | basename }}"
    path: "{{ item.path }}"
    link: "/usr/bin/{{ item.path | basename }}"
  with_items: "{{ imagemagick_binaries.files }}"
  tags: imagemagick
